### ISSUE TITLE
Publish a parser to npm

### ISSUE THREAD

**Issue by ghost** [fuhrmanator/GIFT-grammar-PEG.js#14]
It would be handy to publish a parser generated from the grammar on npm. Maybe it could be named simply gift-parser  or gift-js maybe a reference to peg.js should be included.

**Comment by fuhrmanator** [comment]
That's a great idea. I'm an npm newbie (relatively). I understand how to publish the parser as you suggested, but I am not sure how to automate the creation of the generated parser each time I update the grammar (looking for something automated). 

My online editor just loads the grammar and builds the parser dynamically. I was trying to avoid generating the parser separately because of the syncing issue.  I don't want to do this each time by hand. Any suggestions?

**Comment by ghost** [comment]
You can create a [npm-script](https://docs.npmjs.com/misc/scripts) called prepare, that will be run before publishing the package.
>Run both BEFORE the package is packed and published, and on local npm install without any arguments (See below).

Maybe something like this:
```json
"scripts": {
    "build": "build the parser with peg.js",
    "prepare": "cross-env NODE_ENV=production npm run build",
    "watch": "something that build the parsre on grammar change"
}
```

However I don't know which format should be used for the generated parser: commonjs, umd or es(dev version of peg.js).

**Comment by fuhrmanator** [comment]
Thanks! I already got the build working (based on [this file](https://github.com/thorbenvh8/pegjs-java/blob/master/package.json)). 

However, I'm stuck because my `package.json` which has lots of dependencies for unit testing, running my validator on localhost, etc. is not really what I want to use for the npm publish (it should **only** have a dependency for pegjs).

I could fix it by using a separate `package.json` in the subfolder that gets the built parser. However, it seems strange to have to maintain the project versions in **two** separate files.

**Comment by fuhrmanator** [comment]
Ok, I just found `devDependencies` in the `package.json` -- the example was https://github.com/for-GET/core-pegjs/blob/master/package.json

I'll try to make this happen today.

**Comment by fuhrmanator** [comment]
OK - want to test it for me? https://www.npmjs.com/package/gift-pegjs

**Comment by ghost** [comment]
Thanks, for doing this, I'll try it tomorrow, it's late in France.

**Comment by fuhrmanator** [comment]
OK - closing this now. Let me know here if there are problems.

**Comment by ghost** [comment]
OK thanks for your fast reply, I'll go back on this when I'll get more time. However why didn't you published it on npm.

**Comment by fuhrmanator** [comment]
@benjaminabel I think it's there at https://www.npmjs.com/package/gift-pegjs -- can you confirm?

**Comment by ghost** [comment]
Thanks @fuhrmanator, it is on npm I just installed it. So you decided to export it as a commonjs module.

**Comment by fuhrmanator** [comment]
@benjaminabel yes, I just took the default for a generated parser. I guess it's really going to depend on how it's going to be used. I'm curious to know what kind of things you would do with such a parser. The project started somewhat as an experiment with PEG.js...

**Comment by ghost** [comment]
I'd like to use it on my static course site to display questions and give students instant feedbacks.

**Comment by fuhrmanator** [comment]
@benjaminabel Thanks for letting me know. I added support for the [html] and other formats, which appear a lot when you export GIFT from Moodle (I did a lot of tests with my Moodle question bank). The latest version probably broke any code you had from last week, since the text fields all have a "format" element. Let me know if you need something more with respect to the JSON format. Until now, I've not really used the output for anything!
