### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by aescolan** [fuhrmanator/GIFT-grammar-PEG.js#35]
I just installed gift-pegjs in a Electron program and although it works perfectly, I miss being able to locate in which line or question parsing error occurs.  I have searched but found no references to error management. Where could I find documentation?

Best regards

Alfonso

**Comment by fuhrmanator** [comment]
Hello - sorry for the late reply. Have a look at the [editor code to handle it](https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/ec54a4705b093b929b0e81d9eb26bf5964e4974a/docs/editor/editor.js#L36). 

You might want to look/ask in the [pegjs project](https://github.com/pegjs/pegjs).

Since you're using Electron, you might have a look at [this VSCode extension](https://github.com/ethan-ou/vscode-gift/blob/cf15d8f7216a3fb6738e63f984d60ac0b9d80ef7/server/src/server.ts#L129) that uses the parser to do syntax highlighting and error detecting.

I'm closing since the upstream project should provide better examples or documentation (but it's struggling with a maintainer).
